# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keith/Documents/Capstone/Tools/CoveragePlanner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keith/Documents/Capstone/Tools/CoveragePlanner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keith/Documents/Capstone/Tools/CoveragePlanner/CMakeFiles /home/keith/Documents/Capstone/Tools/CoveragePlanner/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keith/Documents/Capstone/Tools/CoveragePlanner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CoveragePlanner

# Build rule for target.
CoveragePlanner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CoveragePlanner
.PHONY : CoveragePlanner

# fast build rule for target.
CoveragePlanner/fast:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/build
.PHONY : CoveragePlanner/fast

src/bcd.o: src/bcd.cc.o

.PHONY : src/bcd.o

# target to build an object file
src/bcd.cc.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/bcd.cc.o
.PHONY : src/bcd.cc.o

src/bcd.i: src/bcd.cc.i

.PHONY : src/bcd.i

# target to preprocess a source file
src/bcd.cc.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/bcd.cc.i
.PHONY : src/bcd.cc.i

src/bcd.s: src/bcd.cc.s

.PHONY : src/bcd.s

# target to generate assembly for a file
src/bcd.cc.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/bcd.cc.s
.PHONY : src/bcd.cc.s

src/cgal_comm.o: src/cgal_comm.cc.o

.PHONY : src/cgal_comm.o

# target to build an object file
src/cgal_comm.cc.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/cgal_comm.cc.o
.PHONY : src/cgal_comm.cc.o

src/cgal_comm.i: src/cgal_comm.cc.i

.PHONY : src/cgal_comm.i

# target to preprocess a source file
src/cgal_comm.cc.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/cgal_comm.cc.i
.PHONY : src/cgal_comm.cc.i

src/cgal_comm.s: src/cgal_comm.cc.s

.PHONY : src/cgal_comm.s

# target to generate assembly for a file
src/cgal_comm.cc.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/cgal_comm.cc.s
.PHONY : src/cgal_comm.cc.s

src/decomposition.o: src/decomposition.cc.o

.PHONY : src/decomposition.o

# target to build an object file
src/decomposition.cc.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/decomposition.cc.o
.PHONY : src/decomposition.cc.o

src/decomposition.i: src/decomposition.cc.i

.PHONY : src/decomposition.i

# target to preprocess a source file
src/decomposition.cc.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/decomposition.cc.i
.PHONY : src/decomposition.cc.i

src/decomposition.s: src/decomposition.cc.s

.PHONY : src/decomposition.s

# target to generate assembly for a file
src/decomposition.cc.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/decomposition.cc.s
.PHONY : src/decomposition.cc.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sweep.o: src/sweep.cc.o

.PHONY : src/sweep.o

# target to build an object file
src/sweep.cc.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/sweep.cc.o
.PHONY : src/sweep.cc.o

src/sweep.i: src/sweep.cc.i

.PHONY : src/sweep.i

# target to preprocess a source file
src/sweep.cc.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/sweep.cc.i
.PHONY : src/sweep.cc.i

src/sweep.s: src/sweep.cc.s

.PHONY : src/sweep.s

# target to generate assembly for a file
src/sweep.cc.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/sweep.cc.s
.PHONY : src/sweep.cc.s

src/tcd.o: src/tcd.cc.o

.PHONY : src/tcd.o

# target to build an object file
src/tcd.cc.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/tcd.cc.o
.PHONY : src/tcd.cc.o

src/tcd.i: src/tcd.cc.i

.PHONY : src/tcd.i

# target to preprocess a source file
src/tcd.cc.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/tcd.cc.i
.PHONY : src/tcd.cc.i

src/tcd.s: src/tcd.cc.s

.PHONY : src/tcd.s

# target to generate assembly for a file
src/tcd.cc.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/tcd.cc.s
.PHONY : src/tcd.cc.s

src/visibility_graph.o: src/visibility_graph.cc.o

.PHONY : src/visibility_graph.o

# target to build an object file
src/visibility_graph.cc.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/visibility_graph.cc.o
.PHONY : src/visibility_graph.cc.o

src/visibility_graph.i: src/visibility_graph.cc.i

.PHONY : src/visibility_graph.i

# target to preprocess a source file
src/visibility_graph.cc.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/visibility_graph.cc.i
.PHONY : src/visibility_graph.cc.i

src/visibility_graph.s: src/visibility_graph.cc.s

.PHONY : src/visibility_graph.s

# target to generate assembly for a file
src/visibility_graph.cc.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/visibility_graph.cc.s
.PHONY : src/visibility_graph.cc.s

src/visibility_polygon.o: src/visibility_polygon.cc.o

.PHONY : src/visibility_polygon.o

# target to build an object file
src/visibility_polygon.cc.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/visibility_polygon.cc.o
.PHONY : src/visibility_polygon.cc.o

src/visibility_polygon.i: src/visibility_polygon.cc.i

.PHONY : src/visibility_polygon.i

# target to preprocess a source file
src/visibility_polygon.cc.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/visibility_polygon.cc.i
.PHONY : src/visibility_polygon.cc.i

src/visibility_polygon.s: src/visibility_polygon.cc.s

.PHONY : src/visibility_polygon.s

# target to generate assembly for a file
src/visibility_polygon.cc.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/visibility_polygon.cc.s
.PHONY : src/visibility_polygon.cc.s

src/weakly_monotone.o: src/weakly_monotone.cc.o

.PHONY : src/weakly_monotone.o

# target to build an object file
src/weakly_monotone.cc.o:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/weakly_monotone.cc.o
.PHONY : src/weakly_monotone.cc.o

src/weakly_monotone.i: src/weakly_monotone.cc.i

.PHONY : src/weakly_monotone.i

# target to preprocess a source file
src/weakly_monotone.cc.i:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/weakly_monotone.cc.i
.PHONY : src/weakly_monotone.cc.i

src/weakly_monotone.s: src/weakly_monotone.cc.s

.PHONY : src/weakly_monotone.s

# target to generate assembly for a file
src/weakly_monotone.cc.s:
	$(MAKE) -f CMakeFiles/CoveragePlanner.dir/build.make CMakeFiles/CoveragePlanner.dir/src/weakly_monotone.cc.s
.PHONY : src/weakly_monotone.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CoveragePlanner"
	@echo "... src/bcd.o"
	@echo "... src/bcd.i"
	@echo "... src/bcd.s"
	@echo "... src/cgal_comm.o"
	@echo "... src/cgal_comm.i"
	@echo "... src/cgal_comm.s"
	@echo "... src/decomposition.o"
	@echo "... src/decomposition.i"
	@echo "... src/decomposition.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sweep.o"
	@echo "... src/sweep.i"
	@echo "... src/sweep.s"
	@echo "... src/tcd.o"
	@echo "... src/tcd.i"
	@echo "... src/tcd.s"
	@echo "... src/visibility_graph.o"
	@echo "... src/visibility_graph.i"
	@echo "... src/visibility_graph.s"
	@echo "... src/visibility_polygon.o"
	@echo "... src/visibility_polygon.i"
	@echo "... src/visibility_polygon.s"
	@echo "... src/weakly_monotone.o"
	@echo "... src/weakly_monotone.i"
	@echo "... src/weakly_monotone.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

